### PR TITLE
default to guessing the type

### LINKED ISSUE #12: Guess the type if not specified
It is annoying to do `hyperparam(:foo)` where `foo` was a Integer, but it defaulted to `Float64`.
I think the better behavour would be to:
`tryparse` as a `Int` then if that failes `tryparse` as a `Float64`, then if that fails, assume it is a `String`.

This would be a breaking change, though i doublt it would break much code at all.
It would only break code that had a hyperparam that was specified if it were an int (so no decimal point) and was relying on `hyperparam(:foo)` converting it to a `Float64`.

This would also go well as an enhancement to #11  so that it would not just assume everything is an String.

### PR DESCRIPTION
**Pull request by oxinabox**
closes #12 

if #11 is merged then this should be rebased and updated to also guess the type of all variables it is reading from the enviroment.

### CODE REVIEW

File: src/Hyperparameters.jl [hunk 1]
```diff
@@ -56,7 +58,7 @@ hyperparam(:power_level; prefix="HP_")
 ```
 """
 function hyperparam(name::Symbol; prefix::AbstractString=SAGEMAKER_PREFIX)
-    return hyperparam(Float64, name; prefix=prefix)
+    return hyperparam(nothing, name; prefix=prefix)
 end
```
Comment (morris25) [inline src/Hyperparameters.jl:69]:
```suggestion
end

```

File: src/Hyperparameters.jl [hunk 2]
```diff
@@ -70,6 +72,23 @@ function hyperparam(::Type{String}, name::Symbol; prefix::AbstractString=SAGEMAK
...
 
+function hyperparam(::Nothing, name::Symbol; prefix::AbstractString=SAGEMAKER_PREFIX)
+    # this one is adaptive to try and work out the type from the string.
+    value = _parse_hyper(_get_hyperparam(name, prefix))
+    _set_hyperparam(name, value)
+    return value
+end
+
+"guesses the type of the value string and parses as that."
```
Comment (morris25) [inline src/Hyperparameters.jl]:
```suggestion
"""
    _parse_hyper(value_string)
    
Guesses the type of the `value_string` and parses as that.
"""
```

**Review by morris25 — APPROVED** [review]
